spring:
  #数据库连接池类型
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp1cj7wc769f65lfbdo.mysql.rds.aliyuncs.com:3306/taling
    username: taling
    password: taling@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  redis:
    #redis模式选择 single 为单机模式 sentinel 为主从模式
    model: sentinel
    #单机配置
    # Redis数据库索引（默认为 0）
    database: 0
    # Redis服务器地址
    host: 47.115.81.246
    # Redis服务器连接端口
    port: 6379
    # Redis 密码
    password:
    # 连接超时时间（毫秒）
    timeout: 0
    jedis:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 8
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 2000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
    #redis高可用配置
    sentinel:
      #这个值与redis安装配置文件有关
      master: redis_6379
      nodes: 47.115.81.246:26379,47.115.81.246:26380,47.115.81.246:26381

