spring:
  profiles:
    active: dev
  application:
    name: taling-show
  # elasticsearch 配置
  data:
    elasticsearch:
      cluster-name: my-es
      cluster-nodes: 47.115.81.246:9300

server:
  port: 8888

  # thymeleaf模板配置
  thymeleaf:
    cache: false
    mode: HTML5
    check-template: true
    servlet:
      content-type: text/html
    encoding: UTF-8
    suffix: .html
    prefix: classpath:/templates/

mybatis-plus:
  # 实体类扫描路径
  type-aliases-package: org.chenfeng.taling.*.entity
  #xml扫描路径
  mapper-locations: classpath:/mapping/*.xml
  configuration:
    jdbc-type-for-null: null
    global-config:
      # 关闭 mybatis-plus的 banner
      banner: false
    #驼峰下划线映射
    map-underscore-to-camel-case: true
system:
  access:
    filter:
      ignore-urls: /v2/**,/webjars/**,/swagger-resources/**,/doc**,/jq-module/**,/assets/**,/json/**,/pages/**,/login,/register,/captcha,/favicon.ico
#配置sql日志输出
logging.level.org.chenfeng.taling.mapper: debug