#定义页面模板返回前缀和后缀
# 定位模板的目录
spring:
  mvc:
    view:
      prefix: classpath:/templates/
  # 给返回的页面添加后缀名
      suffix: .html
#页面模板是否使用缓存
    cache: false

  #数据库连接池类型
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/taling
    username: root
    password: root123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  #热部署配置
  devtools:
    add-properties: true
    #重启范围
    restart:
      additional-paths: src/main/java
  thymeleaf:
    cache: false
    mode: HTML5
    check-template: true
    servlet:
      content-type: text/html
    encoding: UTF-8

  redis:
    #redis模式选择 single 为单机模式 sentinel 为主从模式
    model: single
    #单机配置
    # Redis数据库索引（默认为 0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis 密码
    password:
    # 连接超时时间（毫秒）
    timeout: 0
    jedis:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 8
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 2000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
    #redis高可用配置
    sentinel:
      master: redis_sentinel
      nodes: 127.0.0.1:26379,127.0.0.1:26380,127.0.0.1:26381



#配置mybatis的 mapper路径
mybatis:
  mapper-locations: classpath:/mapping/*.xml
  #开启驼峰映射
  configuration:
    map-underscore-to-camel-case: true

#pagehelper分页
pagehelper:
  helper-dialect: mysql
  params: countSql
  reasonable: true
  support-methods-arguments: true
